require 'rubygems'
require 'bundler'

Bundler.setup

require 'rake'
require 'spec/rake/spectask'

THIN_OPTIONS = {
                 :address     => '0.0.0.0', 
                 :rackup      => 'config.ru',
                 :port        => 3001,
                 :environment => 'development',
               }

task :default => :specs

desc "Run all examples"

Spec::Rake::SpecTask.new('spec') do |t|
  puts "running specs"
  t.spec_opts = ["--colour --format=nested"]
  t.spec_files = FileList['spec/**/*.rb']
end

namespace :thin do
  task :start do
    puts "Thin starting at #{THIN_OPTIONS[:address]}:#{THIN_OPTIONS[:port]}, logging to #{THIN_OPTIONS[:log]}"
    FileUtils.mkdir_p('log')
    FileUtils.mkdir_p('pid')
    require 'thin'
    controller = Thin::Controllers::Controller.new(THIN_OPTIONS)
    controller.start
  end

  task :stop do
    require 'thin'
    controller = Thin::Controllers::Controller.new(THIN_OPTIONS)
    controller.stop
  end
end

